export type ProviderCost = {
  input_tokens: number;
  output_tokens: number;
  tool_calls: number;
  input_cost: number;
  output_cost: number;
  tool_cost: number;
  total_cost: number;
  currency: string;
};

export type ProviderSnapshot = {
  name: string;
  status: string;
  progress: number;
  last_message?: string | null;
  tool_calls?: number;
  companies_found?: number;
  errors?: string[];
  cost?: ProviderCost | null;
};

export type RunSnapshot = {
  run_id: string;
  project_id: string;
  status: string;
  phase: string;
  percent_complete: number;
  started_at: string;
  finished_at?: string | null;
  config_path?: string | null;
  params?: Record<string, unknown>;
  report_path?: string | null;
  providers: Record<string, ProviderSnapshot>;
  last_event?: Record<string, unknown> | null;
  total_cost?: number;
  cost_currency?: string;
};

export type RunEvent = {
  ts: string;
  type: string;
  [key: string]: unknown;
};

// ============================================================================
// Review System Types
// ============================================================================

export type ReviewStatus = 'pending' | 'approved' | 'rejected' | 'maybe' | 'needs_review';

export type DataQualityFlag = 
  | 'missing_website' 
  | 'missing_financials' 
  | 'missing_team' 
  | 'missing_swot'
  | 'low_confidence' 
  | 'incorrect_data';

export interface CompanyReview {
  company: string;
  status: ReviewStatus;
  score?: number;           // 1-5 investment score
  notes: string;
  dataFlags: DataQualityFlag[];
  reviewedAt: string;
  reviewedBy?: string;
  dataEdits?: Record<string, string>;  // Field overrides
}

export interface ReviewState {
  reviews: Record<string, CompanyReview>;
  currentIndex: number;
  filterStatus: ReviewStatus | 'all' | 'flagged';
  sortBy: 'confidence' | 'name' | 'status' | 'score';
}

export type ReviewAction =
  | { type: 'SET_STATUS'; company: string; status: ReviewStatus }
  | { type: 'SET_SCORE'; company: string; score: number }
  | { type: 'SET_NOTES'; company: string; notes: string }
  | { type: 'ADD_FLAG'; company: string; flag: DataQualityFlag }
  | { type: 'REMOVE_FLAG'; company: string; flag: DataQualityFlag }
  | { type: 'SET_DATA_EDIT'; company: string; field: string; value: string }
  | { type: 'SET_FILTER'; filter: ReviewStatus | 'all' | 'flagged' }
  | { type: 'SET_SORT'; sortBy: 'confidence' | 'name' | 'status' | 'score' }
  | { type: 'SET_INDEX'; index: number }
  | { type: 'NEXT' }
  | { type: 'PREV' }
  | { type: 'LOAD_REVIEWS'; reviews: Record<string, CompanyReview> }
  | { type: 'CLEAR_ALL' };

// ============================================================================
// Project System Types
// ============================================================================

export type ProjectStatus = 
  | 'draft'           // Brief created, not yet started
  | 'test_run'        // Test run in progress
  | 'pending_approval'// Test run complete, awaiting user approval
  | 'researching'     // Discovery research in progress
  | 'discovery_failed' // Discovery failed, can retry
  | 'discovery_complete' // Discovery complete, awaiting deep research decision
  | 'deep_researching'   // Deep research in progress
  | 'ready_for_review'// Research complete, ready for company review
  | 'completed';      // All companies reviewed

export interface ResearchBrief {
  objective: string;
  targetStages: string[];      // e.g., ['seed', 'series_a']
  investmentSize: string;      // e.g., '€500K - €2M'
  geography: string[];         // e.g., ['Western Europe', 'UK']
  technologies: string[];      // e.g., ['IoT', 'AI', 'sustainability']
  additionalNotes: string;
}

export interface KPI {
  name: string;
  target: string;
  rationale: string;
}

export interface ValueChainSegment {
  segment: string;
  description: string;
  companyCount?: number;
}

export interface ResearchFramework {
  thesis: string;
  kpis: KPI[];
  valueChain: ValueChainSegment[];
}

export interface ProjectCost {
  totalCost: number;
  discoveryCost: number;
  deepResearchCost: number;
  enrichmentCost: number;
  currency: string;
  lastUpdated?: string;
}

export interface ProjectStats {
  totalCompanies: number;
  enrichedCompanies: number;
  approved: number;
  rejected: number;
  maybe: number;
  pending: number;
  flagged: number;
}

export interface Project {
  id: string;
  
  // Client context
  clientName: string;
  projectName: string;
  
  // Research brief (user input)
  brief: ResearchBrief;
  
  // AI-generated frameworks (editable)
  framework: ResearchFramework;
  
  // Research state
  status: ProjectStatus;
  reportPath?: string;
  testRunReportPath?: string;
  
  // Stats
  stats: ProjectStats;
  
  // Cost tracking
  cost?: ProjectCost;
  
  // Archive state
  archived?: boolean;
  archivedAt?: string;
  
  // Timestamps
  createdAt: string;
  updatedAt: string;
}

// Clarifying questions generated by AI
export interface ClarifyingQuestion {
  id: string;
  question: string;
  type: 'single_choice' | 'multiple_choice' | 'text' | 'range';
  options?: string[];
  answer?: string | string[];
}

export interface TestRunCompany {
  company: string;
  segment: string;
  summary?: string;
  country?: string;
  confidence_0to1?: number;
}

